name: Test and deploy

on:
  push:
    branches:
      - master

jobs:
  test_and_build:
    name: Run Test And Build docs playground
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Build hooks
      #   run: npm run build-hooks

      # 测试
      - name: Run tests
        run: npm run test
      
      # 打包
      - name: Build docs
        run: npm run docs:build
      
      - name: Build Playground
        run: npm run storybook:build

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./packages/docs/.vitepress/dist
      
      - name: Upload playgound
        uses: actions/upload-artifact@v3
        with:
          name: playground
          path: ./packages/playground/storybook-static/

      
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test_and_build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Markdown to HTML converter
        run: npm install -g showdown
      # 这里清除了根目录无关文件 提到最前执行
      - name: Convert README.md to HTML
        run: |
          showdown makehtml -i README.md -o index.html
          find . -mindepth 1 ! -name 'index.html' -exec rm -rf {} +

      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: docs
          path: ./docs

      - name: Download playground
        uses: actions/download-artifact@v3
        with:
          name: playground
          path: ./playground

      - name: Deploy README.md
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./


      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs

      - name: Deploy playground to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./playground
          destination_dir: playground
